### ISSUE TITLE
Mod Items not displaying data or dumping data from HxCEnchants V2

### ISSUE THREAD

**Issue by plazia** [HxCKDMS/HxCEnchants#23]
NPE on Piercing enchant caused by old code from v1  :  http://pastebin.com/7bLDu7fC
FIXED

**Comment by DrZed** [comment]
disable piercing enchant for now I know what happened I'll fix when done

**Comment by plazia** [comment]
Stack Overflow on Flaming enchant level too high caused by Draconic Bow http://pastebin.com/fGg4jbLD
FIXED

**Comment by DrZed** [comment]
Ummm
Don't use that enchant with draconic evolution....

**Comment by DrZed** [comment]
Gonna see if I can set a MAX level for it .... because Draconic evolution Doubles/Triples the level of an enchant... Getting too high on that enchant = 19x19 area of fire every tick...

**Comment by DrZed** [comment]
disable the enchant to remove the fire from world if ti still crashes

**Comment by plazia** [comment]
EnderIO Chestplate Draining Charge to -5 every time it's filled

Draconic Evolution Wyvern sword doesn't even show the xp charge in its tooltip. < Can't be fixed Draconic Evolution overrides the tooltip method and clears and adds its own tooltip

Hmmm enchanting+ used to work flawlessly with your mod. I wish there was some way of getting them to both work perfectly together or at least more harmoniously. 

Keybinds disabling didn't fix crash with Okushama's NEK
FIXED with disabling config

**Comment by DrZed** [comment]
Hmmm...

**Comment by DrZed** [comment]
Went on an editing spree so I could understand what bugs are in this issue report and what has been fixed

**Comment by DrZed** [comment]
Some mod items don't like having unknown data put on them... ? IDK what to entirely do to fix that if I can..

**Comment by DrZed** [comment]
http://game.kappador.com:5050 Jenkins to grab latest builds

**Comment by DrZed** [comment]
I added a config option to not even register the keybinds to the game also the same goes for all my enchants if you disable they don't register

**Comment by DrZed** [comment]
Draconic Evolution Wyvern sword doesn't even show the xp charge in its tooltip. < Can't be fixed Draconic Evolution overrides the tooltip method and clears and adds its own tooltip

I can add a command to check the charge??? or on screen display (if I figure out gui code :)

**Comment by DrZed** [comment]
EnderIO Chestplate Draining Charge to -5 every time it's filled

Has a chance to be my fault I'll have to do some testing

**Comment by DrZed** [comment]
Hmmm enchanting+ used to work flawlessly with your mod. I wish there was some way of getting them to both work perfectly together or at least more harmoniously.

I broke compat by breaking away from vanilla code, I'll re-instate compatability when I recode enchanting plus

**Comment by DrZed** [comment]
Also Plazia What's your ingame name I wanna add you to HxCSupport list :D

**Comment by DrZed** [comment]
9ae538d0-32ee-41cd-b39d-fdab46521290 Your UUID I'll add it to the list just lemme know if you want to have [HxC Support] beside your name in game

**Comment by DrZed** [comment]
@plazia hello?

**Comment by plazia** [comment]
in game name is plazia and thanks. I've been trying your latest release and no such problems with the keybindings now. Also seems you've sorted out Enchanting+. Thanks very much.

**Comment by DrZed** [comment]
:D so would you let me add you to HxCSupporters list? I ask nothing of you it's just you brought a bunch of bugs to mind :D

Just restart your game/server to show the change if someone looks at you or you talk in chat it should now show [HxC Supporter] or something similar

**Comment by plazia** [comment]
Sure why not. If I find any more bugs of interest I shall report them to you with haste. :)
